---
# defaults file for guardian

guardian_version: au1.6.2
guardian_archive_name: aurum-{{ guardian_version }}.tar.gz
guardian_bin_name: cube-aurum
guardian_app_environment: production
guardian_access_token: "{{ guardian_access_token_vault }}"
# guardian_access_token_vault: "my_guardian_access_token"

# rust_backtrace: "full"

# guardian_service_state: stopped

guardian_user:
  name: "cube-guardian-{{ guardian_instance.guardian_id }}"
  group: "cube-guardian-{{ guardian_instance.guardian_id }}"
  create_home: false
  password: "!"
  shell: /usr/sbin/nologin
  system: true

guardian_listen_node_interface: "{{ ansible_default_ipv4.interface }}"
# guardian_listen_node_interface: enp2s0
guardian_listen_node_ip: "{{ hostvars[inventory_hostname]['ansible_' ~ guardian_listen_node_interface]['ipv4']['address'] }}"
guardian_listen_node_port: 9420
# guardian_listen_node_port_open_iptables: true

guardian_listen_web_interface: "{{ ansible_default_ipv4.interface }}"
# guardian_listen_web_interface: enp2s0
guardian_listen_web_ip: "{{ hostvars[inventory_hostname]['ansible_' ~ guardian_listen_web_interface]['ipv4']['address'] }}"
guardian_listen_web_port: 443
# guardian_listen_web_port_open_iptables: true

guardian_listen_webadmin_interface: "{{ ansible_default_ipv4.interface }}"
# guardian_listen_webadmin_interface: enp2s0
guardian_listen_webadmin_ip: "{{ hostvars[inventory_hostname]['ansible_' ~ guardian_listen_webadmin_interface]['ipv4']['address'] }}"
guardian_listen_webadmin_port: 10443

guardian_dirs:
  install: "/opt/cube-guardian-{{ guardian_instance.guardian_id }}/bin"
  config: "/opt/cube-guardian-{{ guardian_instance.guardian_id }}/config"
  log: "/var/log/cube-guardian-{{ guardian_instance.guardian_id }}"

# Deploy script to copy certificates and chown after certbot renewal
deploy_certbot_renewal_hook: false

guardian_certificates:
  remote_path: "/etc/letsencrypt/live/{{ guardian_instance.public_fqdn }}"
  tls_private_key_name: "privkey.pem"
  tls_certificate_name: "fullchain.pem"
  tls_root_certificate_name: "fullchain.pem"

guardian_use_ca_bundle: false
guardian_ca_bundle_file: "guardian_ca_bundle.pem"
guardian_ca_bundle_dest: "{{ guardian_dirs.config }}/{{ guardian_ca_bundle_file }}"

guardian_instance:
  guardian_id: 000
  public_fqdn: example-guardian-1.testing.cube.exchange

guardian_config_main:
  cube_id: 100
  key_path: "{{ guardian_dirs.config }}/{{ guardian_certificates.tls_private_key_name }}"
  certs_path: "{{ guardian_dirs.config }}/{{ guardian_certificates.tls_certificate_name }}"
  roots_path: "{{ guardian_dirs.config }}/{{ guardian_certificates.tls_root_certificate_name }}"

guardian_approle_copy_remote_src: /opt/cube-vault-configs

vault_cluster_fqdn: "example.hashicorp.vault.cluster.com"
self_signed_certs_local_dir: "{{ inventory_dir }}/hashicorp-vault-certs"
self_signed_cert_files:
  ca_cert: "{{ vault_cluster_fqdn }}.ca.cert.pem"

guardian_key_storage:
  hashicorp_vault:
    secret_mount_path: "cube-guardian/guardian-{{ guardian_instance.guardian_id }}"
    approle_path_reader: "{{ guardian_dirs.config }}/vault.guardian.{{ inventory_hostname }}.reader.json"
    approle_path_writer: "{{ guardian_dirs.config }}/vault.guardian.{{ inventory_hostname }}.writer.json"
    approle_token_renew_seconds: 3600
    vault_url: "https://example-vault-1.example.hashicorp.vault.cluster.com:8200"
    vault_tls_client_ca_filename: "{{ self_signed_cert_files.ca_cert }}"
    vault_tls_client_ca_local_source_dir: "{{ inventory_dir }}/hashicorp-vault-certs"
    access_log_filename: "access.json"

guardian_config_manager:
  num_workers: 16
  max_active_triple_jobs: 16
  num_triples_to_cache: 256
  public_shares_path: "{{ guardian_dirs.config }}/public_shares.json"
  cached_triples_path: "{{ guardian_dirs.config }}/triples.json"

guardian_web_btc_network: "Mainnet"

logrotate_enable: true
logrotate_keep_days: 14
