- name: Deploy Guardian
  # Update hosts selector with new guardian hostname
  # Ensure host_vars folder matches when changed
  hosts: example-guard-1
  gather_facts: false
  become: true
  become_user: root
  pre_tasks:
    - name: Gather OS Family
      ansible.builtin.setup:
        gather_subset:
          - os_family
  roles:
    - role: geerlingguy.swap
      tags: swap
    - role: geerlingguy.certbot
      tags: certbot
    - role: cubexch.guardian.guardian_vault_config
      tags: guardian_vault_config
    - role: cubexch.guardian.guardian
      tags: guardian
